/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefence;

import gameElements.OverlayPanel;
import gameElements.Playfield;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Point2D;
import tower.TowerHandler;

/**
 *
 * @author Glenn Latomme <glenn.latomme@gmail.com>
 */
public class Game extends javax.swing.JPanel implements Runnable {
    
    Thread Th;
    double Dtime;
    // Gamefield
    Playfield Playfield = new Playfield(100, 100);
    // Overlay
    public boolean EscIsPressed = false;
    OverlayPanel OverlayPanel = new OverlayPanel();
    //Towers
    TowerHandler TowerHandeler = new TowerHandler();
    
    public Game() {
        initComponents();
        Th = new Thread(this);
        Th.start();
        TowerHandeler.setPlayfield(Playfield);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (EscIsPressed) {
            OverlayPanel.MouseClicked(evt);
        }
        
        Point2D.Double pt = new Point2D.Double(evt.getX(), evt.getY());
        TowerHandeler.addTower(pt);
        
        System.out.println("Rown nr: " + Playfield.getRowNR((int) pt.getX()) + " Kolum nr: " + Playfield.getRowNR((int) pt.getY()));
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {
        while (true) {
            Tick();
            repaint();
            Dtime = 0;
        }
    }
    
    private void Tick() {
        if (EscIsPressed == false) {
            Playfield.tick();
            TowerHandeler.tick();
        } else {
            OverlayPanel.tick();
        }
    }
    
    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        // clear screen
        ClearScrean(g2);

        // paint stuff
        Playfield.paint(g2);
        TowerHandeler.paint(g2);
        if (EscIsPressed) {
            OverlayPanel.paint(g2);
        }
    }
    
    private void ClearScrean(Graphics2D g) {
        Color c = getBackground();
        Dimension d = getSize();
        g.setColor(c);
        g.fillRect(0, 0, d.width, d.height);
        g.setColor(Color.BLACK);
    }
}
