/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package towerdefence;

import java.awt.*;
import towerdefence.Button;

/**
 *
 * @author Glenn Latomme <glenn.latomme@gmail.com>
 */
public class OverlayMenu extends javax.swing.JPanel {

    /**
     * Creates new form OverlayMenu
     */
    Button btnQuit = new Button(Toolkit.getDefaultToolkit().getScreenSize().width/2 - 50, Toolkit.getDefaultToolkit().getScreenSize().height/2 - 15, "./src/img/Quit.png", "./src/img/QuitHover.png");
    
    public OverlayMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(getSize());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        if (btnQuit.hoverover(evt.getX(), evt.getY())){
            System.exit(0);
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        DrawField(g);
        btnQuit.paint(g);
    }
    private void DrawField(Graphics g) {
        // Clear the screen
        // Init color     
        Color Background = new Color(0,0,0,100);
        g.setColor(Background);
        
        // Draw
        g.fillRect(0, 0, getWidth(), getHeight());
    }
}
